apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tq1t1ich0-python 
  janus-idp.io/tekton: tq1t1ich0-python
  backstage.io/kubernetes-id: tq1t1ich0-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tq1t1ich0-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml